export const ADD_CANDIDATE_TO_CART = "ADD_CANDIDATE_TO_CART";
export const LOAD_FAVORITED_CANDIDATES = "LOAD_FAVORITED_CANDIDATES";
export const LOAD_MEORASIM = "LOAD_MEORASIM";
export const CLOSE_MATCH = "CLOSE_MATCH";


export default {
    ADD_CANDIDATE_TO_CART,
    LOAD_FAVORITED_CANDIDATES,
    LOAD_MEORASIM,
    CLOSE_MATCH
}