export const USER_LOGIN = 'USER_LOGIN';
export const LOAD_CANDIDATES = "LOAD_CANDIDATES";
export const DELETE_CANDIDATE = "DELETE_CANDIDATE";

export default {
    USER_LOGIN,
    LOAD_CANDIDATES,
    DELETE_CANDIDATE
}