export const USER_LOGIN = 'USER_LOGIN';
export const LOAD_CANDIDATES = "LOAD_CANDIDATES";
export const LOAD_FILTERED_CANDIDATES = "LOAD_FILTERED_CANDIDATES";
export const REMOVE_CANDIDATE = "REMOVE_CANDIDATE";

export default {
    USER_LOGIN,
    LOAD_CANDIDATES,
    LOAD_FILTERED_CANDIDATES,
    REMOVE_CANDIDATE
}