export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const SAVE_MESSAGE = "SAVE_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const LOAD_NEW_CANDIDATES = "LOAD_NEW_CANDIDATES";
export const LOAD_NEW_MATCHMAKERS = "LOAD_NEW_MATCHMAKERS";


export default {
    LOAD_MESSAGES,
    SAVE_MESSAGE,
    DELETE_MESSAGE,
    LOAD_NEW_CANDIDATES,
    LOAD_NEW_MATCHMAKERS,
   
}

